import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { TextSwitch } from '@/components/textswitch/textswitch'
import { Option } from '@/components/textswitch/textSwitchOption'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Component Test Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TextSwitch>
          <Option value="left">LeftLeftLeftLeftLeft</Option>
          <Option value="center">Center</Option>
          <Option value="right">Right</Option>
          <Option value="right4">RightRight</Option>
        </TextSwitch>
      </main>
    </>
  )
}
